#!/bin/bash

# CLI's
DOCKER=docker
ESPTOOL=esptool.py

# ----------------------------------------------------------

# Help screen
help() {
    echo "ESP8266 Build script v0.1"
    echo "Usage: $0 <options>"
    echo "  options:"
    echo "     setup   Build the Docker image and clone the SDK repository in the current folder."
    echo "     all     Build the project and upload it to the device."
    echo "     build   Build the project only."
    echo "     shell   Open an interactive shell inside the container."
    echo 
    echo "Example 1: $0 setup"
    echo "Example 2: $0 all"
    echo "Example 3: $0 buil"
    echo "Example 4: $0 shell"
}

# ----------------------------------------------------------

setup() {
    $DOCKER build -t my-esp8266-build .
    # Check if the docker run command was successful
    if [ $? -eq 0 ]; then
        git clone --recursive https://github.com/espressif/ESP8266_RTOS_SDK.git
    fi
}

# ----------------------------------------------------------

all() {
    
    # Run the docker command, print output to terminal, and capture both stdout and stderr
    echo "Building project..."
    output=$($DOCKER run --rm -v "$PWD":/root/esp/build -w /root/esp/build my-esp8266-build make all 2>&1)

    # Check if the docker run command was successful
    if [ $? -eq 0 ]; then

        # If successful, parse and extract the flashing command
        result=$(echo "$output" | sed -n 's|^.*python /root/esp/ESP8266_RTOS_SDK/components/esptool_py/esptool/esptool.py ||p' | sed 's|/root/esp/build|.|g')
        
        # Output the result
        echo "Uploading project..."
        $ESPTOOL $result
    else
        # If docker run failed, print the error message
        echo "Docker run failed. Here is the error:"
        echo "$output"
        exit 1  # Exit with a non-zero status to indicate failure
    fi
}

# ----------------------------------------------------------

build() {
# Run the docker command, print output to terminal, and capture both stdout and stderr
    echo "Building project..."
    $DOCKER run --rm -v "$PWD":/root/esp/build -w /root/esp/build my-esp8266-build make all
}

# ----------------------------------------------------------

shell() {
    $DOCKER run -it --rm -v "$PWD":/root/esp/build -w /root/esp/build my-esp8266-build /bin/bash
}

# ----------------------------------------------------------

main () {

    POSITIONAL=()
    while [[ $# -gt 0 ]]; do
        key="$1"

        case $key in
        setup)
            ACTION=setup
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        all)
            ACTION=all
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        build)
            ACTION=build
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        shell)
            ACTION=shell
            ACTION_PARAM="$2"
            shift
            shift
            ;;
        *)
            POSITIONAL+=("$1")
            shift
            ;;
        esac
    done

    set -- "${POSITIONAL[@]}" # restore positional parameters

    # Here is positional parameters tail. Basically the last command line argument(s).
    TAIL=$1

    # Check dependency. If 'docker' is here.
    # Normally docker should be here but who knows :)
    if ! hash $DOCKER &>/dev/null; then
        echo "Docker is not installed on Host computer !, Please make sure 'docker' CLI is accessible from shell"
        exit 1
    fi

    # Check dependency. If 'esptool.py' is here.
    # Normally esptool.py should be here but who knows :)
    if ! hash $ESPTOOL &>/dev/null; then
        echo "esptool.py is not installed on Host computer. esptool.py is a command line interface that works with device (flash,erasy, etc)."
        exit 1
    fi

    # Check dependency. If 'git' is here.
    # Normally git should be here but who knows :)
    if ! hash $GIT &>/dev/null; then
        echo "Git is not installed on Host computer. That's weird"
        exit 1
    fi

    # Check action parameter
    if [ "$ACTION" == "" ]; then
        help
        echo "Action must be specified in command line argument !"
        exit 1
    else

        # setup action
        if [ "$ACTION" == "setup" ]; then
            setup;
        fi

        # all action
        if [ "$ACTION" == "all" ]; then
            all;
        fi

        # build action
        if [ "$ACTION" == "build" ]; then
            build;
        fi

        # shell action
        if [ "$ACTION" == "shell" ]; then
            shell;
        fi

        exit 0
    fi

    help;
}

main "$@"


